config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#home'
  get 'about', to: 'welcome#about'

  # Create all endpoints to CRUD articles
  resources :articles

  # Signup
  get 'signup', to: 'users#new'
  resources :users , except: [:new]

  # Login
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'login', to: 'sessions#destroy'


  resources :categories, except: [:destroy]
  #Invitations
  resources :invitations, except: [:edit,:show,:update]
end

app/models/article.rb
class Article < ApplicationRecord

    belongs_to :user
    has_many :article_categories
    has_many :categories , through: :article_categories
    validates :title, presence: true, length: { minimum:3 , maximum: 50 }
    validates :description, presence: true, length:  { minimum:10 , maximum: 100 }
    validates :user_id, presence: true
end

app/controllers/articles_controller.rb
# Language: Ruby, Level: Level 3
class ArticlesController < ApplicationController

    before_action :set_article, only: [:edit,:update,:show, :destroy]
    before_action :require_user, except: [:index, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def index
        #@articles = Article.all;
        @articles = Article.paginate(page: params[:page], per_page: 5)
    end

    def new
        @article = Article.new
    end

    def edit
        #@article = Article.find(params[:id])
    end

    def create


        @article = Article.new(article_params)
        @article.user = current_user

        if @article.save
            flash[:success] = "Article was succesfully created"
            redirect_to article_path(@article)
        else
            render :new
        end

        #redirect_to articles_path(@article)
    end

    def show
        #@article = Article.find(params[:id])
    end

    def update
        #@article = Article.find(params[:id])
        if @article.update(article_params)
            flash[:success] = "Article was updated"
            redirect_to article_path(@article)
        else
            render 'edit'
        end
    end

    def destroy
        #@article = Article.find(params[:id])
        @article.destroy
        flash[:danger] = "Article was deleted"
        redirect_to articles_path
    end



    private
        def set_article
            @article = Article.find(params[:id])
        end
        def article_params
            #params.require(:article).permit(:title,:description,category_ids: [])
            params.require(:article).permit!
        end

        def require_same_user

          if current_user != @article.user and !current_user.admin?
              flash[:danger] = "You can only edit your own article"
              redirect_to root_path
          end
        end
end

app/views/articles/_article.html.erb
<div class="row">
<% obj.each do |a| %>
  <div class="card col-sm-12 col-md-12" >
    <!--<img class="card-img-top" src="..." alt="Card image cap">-->
    <div class="card-body">
      <h5 class="card-title"><%= link_to a.title, article_path(a)  %></h5>
      <p class="card-text">
        <%= truncate a.description , length: 20 %><br>
        <small>(<%= a.user.username if a.user %>) on <%= time_ago_in_words a.created_at %></small>
        <small>Last update: <%= time_ago_in_words a.updated_at %></small>
      </p>
      <% if a.categories.any? %>
        <p><%= render a.categories %></p>
      <% end %>
      <% if logged_in? && ( current_user == a.user  || current_user.admin? )%>
          <%= link_to "Edit" , edit_article_path(a), class: 'btn btn-primary btn-sm' %>
          <%= link_to "Show" , article_path(a), class: 'btn btn-primary btn-sm' %>
          <%= link_to "Delete" , article_path(a) , class: 'btn btn-danger btn-sm', method: :delete, data: { confirm: "Are you sure?"} %></td>
      <% end %>
    </div>
  </div>

<% end %>
</div>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>
<!-- http://guides.rubyonrails.org/form_helpers.html  -->
<%= form_for @article do |f| %>
    <fieldset class="form-group">
        <label for="exampleInputEmail1"><%= f.label :title %> </label>
        <%= f.text_field :title, class: 'form-control' %>
    </fieldset>
    <fieldset class="form-group">
        <label for="exampleInputEmail1"><%= f.label :description %></label>
        <%= f.text_area :description, class: 'form-control' %>
    </fieldset>
    <fieldset class="form-group">
        <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
          <% cb.label(class: "checkbox-inline input_checkbox") { cb.check_box(class: "checkbox") + cb.text } %>
        <% end %>
    </fieldset>
    <%= f.submit class: 'btn btn-primary btn-large'%>

<% end %>

<p><%= link_to "Back to Articles listing" , articles_path  %></p>

app/views/articles/edit.html.erb
<h2>Edit Article</h2>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>List all articles</h1>

<%= render 'article', obj: @articles %>
<div class="center">
  <%= will_paginate :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer %>
</div>

app/views/articles/new.html.erb
<h1>Create an Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<div><%= @article.description %></div>
<% if @article.categories.any? %>
  <p><%= render @article.categories %>
<% end %>
<% if @article.user %>
 <hr>
  <ul class="listing">
    <duv class="row">

      <div class="well col-md-12">
        <li><%= link_to gravatar_for(@article.user, { size: 30 }), user_path(@article.user) %></li>
        <li class="article-title">
          <%= link_to @article.user.username, users_path(@article.user) %>
        </li>
        <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
      </div>
    </duv>

  </ul>

<% end %>

<% if logged_in? && ( current_user == @article.user || current_user.admin? ) %>
    <p><%= link_to "Edit this article" , edit_article_path(@article)  %></p>
<% end %>

<p><%= link_to "Back to Articles listing" , articles_path  %></p>