config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#home'
  get 'about', to: 'welcome#about'

  # Create all endpoints to CRUD articles
  resources :articles

  # Signup
  get 'signup', to: 'users#new'
  resources :users , except: [:new]

  # Login
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'login', to: 'sessions#destroy'


  resources :categories, except: [:destroy]
  #Invitations
  resources :invitations, except: [:edit,:show,:update]
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <footer class="container">
    <p class="float-right"><a href="#">Back to top</a></p>
    <p>© 2017-2018 Manuel López· <a href="#">Privacy</a> · <a href="#">Terms</a></p>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <div class="alert alert-<%= name %> alert-dismissible fade show" role="alert">
      <%= msg %>
    </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <%= link_to 'Alpha Blog', root_path , class: "navbar-brand", id: "logo"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
        <%= link_to 'Articles', articles_path , class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Bloggers', users_path , class: "nav-link" %>
      </li>



    </ul>
    <ul class="navbar-nav">
        <% if logged_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Actions
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%= link_to 'New article', new_article_path , class: "dropdown-item" %>
                  <%= link_to 'New invitation', new_invitation_path , class: "dropdown-item" %>
              </div>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Categories
              </a>
              <ul class="dropdown-menu">
                  <li><%= link_to 'New category', new_category_path , class: "dropdown-item" if current_user.admin?  %></li>
                  <li><%= link_to 'All categories', categories_path , class: "dropdown-item" %></li>
                  <li role="separator" class="dropdown-divider"></li>
                  <% Category.all.each do |c| %>
                    <li><%= link_to c.name, category_path(c) , class: "dropdown-item" %></li>
                  <% end %>
              </ul>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Your profile <%= "[Admin]" if current_user.admin? %>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%= link_to 'Edit your profile', edit_user_path(current_user) , class: "dropdown-item" %>
                  <%= link_to 'My Home', user_path(current_user), class: 'dropdown-item' %>
              </div>
            </li>
            <li class="nav-item">
              <%= link_to 'Logout', login_path, method: :delete , class: 'nav-link' %>
            </li>

        <% else %>
            <li class="nav-item">
              <%= link_to 'Sign In', login_path , class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign Up', signup_path , class: 'nav-link' %>
            </li>
        <% end %>

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= 'home' if params[:action] == 'home' %>">
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
        <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>